### ISSUE TITLE
Generates a Dockerfile

### ISSUE THREAD

**Issue by mrchypark** [codingpot/github-org-member-manage-action#3]

**Comment by kkweon** [comment]
Dockerfile로 변경했습니다. 

GitHub Action이 실행될때 Dockerfile이 빌드되는 구조이기 때문에 Dockerfile 을 태깅해서 깃헙릴리즈하기만 하면 됩니다.
ghcr.io 로 푸시된 이미지는 실제 릴리즈(깃헙 릴리즈)와 혼란이 있을 수 있을 것 같습니다.

**Comment by mrchypark** [comment]
이해했습니다. 미리 빌드된 이미지를 사용하는 것으로 캐쉬의 역할을 기대할 수 있을 것 같지만, 그건 나중의 일로 미루는 것이 더 좋겠다 싶네요.

**Comment by kkweon** [comment]
Implemented
