### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by kkweon** [codingpot/github-org-member-manage-action#4]
<img src="http://www.plantuml.com/plantuml/svg/bLJHRjim37ptLsXlARRym10O7Pfc6z0kHRDz06CnZX29CYWgwLRit-SgzY9tGe6z-85tF9AwWw-304jqjdedUtIe70YoWRcFOWrX5Gw6Ec1mQWlDeMKVITzuwrcTzaQmggh6GWZgKzTPqu0OJ-gvKkgzuaYpg-htIBZn9FWa2Tm86sfLQsGVjz_z0UbIt1cBYKioBJw0x2ToEzFU0q6BV9uur9OWe1X1hzYxMphEhXAuYX8P5nTE_PVqsSYNk4syeiYTRy0Ey4P0Ob0dDeAp2pSxzAosvdRpavezUpA_XWsNPhTJeQzcZSfR_I4VIdYwYAMMr7jdWYpEhr6_SDOdGWu5u1xTje1ej2WuWhs-8K7UGOF3mXlaesbGFMTdhddnY25QgHK-OHC5PoyBJLu2j1vKP_d0rvoqxniKHkUFM5RAx4l0UU4V0RckqvLZM-v2VjHNrrbb-Wyw90c5Y-TZqg0pAP0NfHKSyB_KnixSrIprdjjluF2rGQxicp_HODWqyVFvlCu7V5GFx7LiC5Jb0AQ65AUtgKNjHmGTIXjCRk-9I-oGT52UgYcKJRyzHodyUr8z_YLwLczlc6gK2DT8EZhx1m00">

* [source](http://www.plantuml.com/plantuml/svg/bLJHRjim37ptLsXlARRym10O7Pfc6z0kHRDz06CnZX29CYWgwLRit-SgzY9tGe6z-85tF9AwWw-304jqjdedUtIe70YoWRcFOWrX5Gw6Ec1mQWlDeMKVITzuwrcTzaQmggh6GWZgKzTPqu0OJ-gvKkgzuaYpg-htIBZn9FWa2Tm86sfLQsGVjz_z0UbIt1cBYKioBJw0x2ToEzFU0q6BV9uur9OWe1X1hzYxMphEhXAuYX8P5nTE_PVqsSYNk4syeiYTRy0Ey4P0Ob0dDeAp2pSxzAosvdRpavezUpA_XWsNPhTJeQzcZSfR_I4VIdYwYAMMr7jdWYpEhr6_SDOdGWu5u1xTje1ej2WuWhs-8K7UGOF3mXlaesbGFMTdhddnY25QgHK-OHC5PoyBJLu2j1vKP_d0rvoqxniKHkUFM5RAx4l0UU4V0RckqvLZM-v2VjHNrrbb-Wyw90c5Y-TZqg0pAP0NfHKSyB_KnixSrIprdjjluF2rGQxicp_HODWqyVFvlCu7V5GFx7LiC5Jb0AQ65AUtgKNjHmGTIXjCRk-9I-oGT52UgYcKJRyzHodyUr8z_YLwLczlc6gK2DT8EZhx1m00)

**Comment by bloomspes** [comment]
그림은 무엇으로 그리셨어요?

**Comment by mrchypark** [comment]
@bloomspes 밑에 소스 링크를 확인해 보시면 plantuml 인거 같습니다. :)

**Comment by deep-diver** [comment]
@kkweon @mrchypark 

[GitHub Organization API 문서](https://docs.github.com/en/rest/reference/orgs)를 보니까 멤버를 "추가" 한다는 개념 보다는 "초대장을 보낸다"는 의미인것 같습니당(초대 보낸 뒤 수락해야 Member가 되는 절차). 상기 UML 에서의 Members 는 초대장을 보내 놓은 Member도 포괄하는 속성일까요?

**Comment by kkweon** [comment]
yaml 에 있고 멤버에 없으면 계속 보냅니다. 그게 declarative 하기 때문에.

**Comment by kkweon** [comment]
Sequence Diagram

<img src="http://www.plantuml.com/plantuml/svg/dP91Qzj048Nl-okcj0SPwakFfPWOnsa2jXEmS-YfZ5SZQSXer-oExBQ_lgkc96iXGl1D-tRcVK-FlOgAGRjMp0Tjg2LeKIamJdsdmevCV69tm80jxD4-rS5thbnuyG5E3Mj-7nii_ObT3HLAJ3SMXU2BCMWrZSyF1s6Bojxza_YOIBdwAYwygxXUeyEQmglydVMsssyf7DdIKBuFzVQtiqtmZlzGI0XH-7ItUNZS_RovMoqNzvlTShC3Ze17PC6za86S3zFPEHc-GY0iRu9lb-vOJ0n9fDppORwxlT1mvIrAR-bA0uEfQThBRVejxOAB_-UkKT6OTuAUsqca0MDsNcVQ48wwfdPF8HOJ-0ZQS7mXemYqpvTGiBC2_kJIOMBERQR3A5dwLG9yUumKPiPSyCSbZJ-GOHNZ3o9vndGigfTEFaF__ME-NatC-CeRkQwvgamMQHGw7Ytld7wHxPIAtcvGvLlqhQ9sCUVdW-QANDcryXS0">

- [source](http://www.plantuml.com/plantuml/svg/dP91Qzj048Nl-okcj0SPwakFfPWOnsa2jXEmS-YfZ5SZQSXer-oExBQ_lgkc96iXGl1D-tRcVK-FlOgAGRjMp0Tjg2LeKIamJdsdmevCV69tm80jxD4-rS5thbnuyG5E3Mj-7nii_ObT3HLAJ3SMXU2BCMWrZSyF1s6Bojxza_YOIBdwAYwygxXUeyEQmglydVMsssyf7DdIKBuFzVQtiqtmZlzGI0XH-7ItUNZS_RovMoqNzvlTShC3Ze17PC6za86S3zFPEHc-GY0iRu9lb-vOJ0n9fDppORwxlT1mvIrAR-bA0uEfQThBRVejxOAB_-UkKT6OTuAUsqca0MDsNcVQ48wwfdPF8HOJ-0ZQS7mXemYqpvTGiBC2_kJIOMBERQR3A5dwLG9yUumKPiPSyCSbZJ-GOHNZ3o9vndGigfTEFaF__ME-NatC-CeRkQwvgamMQHGw7Ytld7wHxPIAtcvGvLlqhQ9sCUVdW-QANDcryXS0)

**Comment by kkweon** [comment]
Implemented
